version: "3"

services:

    api:
        build: .
        restart: always
        container_name: api
        depends_on:
            - postgres
        ports:
            - 8000:8000
        env_file:
            - ./.env
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ./:/usr/src/app

    postgres:
        image: postgres
        restart: always
        container_name: db
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - ./tests/unit_tests/pg-init-script:/docker-entrypoint-initdb.d
            - postgres-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=currency_converter_test

    pgadmin:
        depends_on:
            - postgres
        container_name: pgadmin
        image: dpage/pgadmin4
        env_file:
            - ./.env
        ports:
            - 5050:80
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    postgres-db:
    pgadmin-data: